"""Add banner_filename to Club model

Revision ID: 96bf73c36658
Revises: 87bf41d5002b
Create Date: 2025-11-28 05:29:11.794077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96bf73c36658'
down_revision = '87bf41d5002b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.drop_column('banner_filename')

    # ### end Alembic commands ###
